### PR TITLE
Specified model names and more

### PR DESCRIPTION
**Pull request by Alfrick**

### CODE REVIEW

**Comment by zeiler** [comment]
how come we hard coded specific models into the docs? Some of them even being hashes which don't look good.

**Comment by Alfrick** [comment]
The idea we shared with @iankelk is to have ready, default, copy-paste samples that users can run on the go. We've also inserted comments that point users to where they can make changes and run their own code. Please let us know if you have other thoughts about it.

**Comment by zeiler** [comment]
i thought we wanted to leave all the code snippets as templates so that we can ingest them into the UI and string replace the template variables with actual models. That would allow people to easily find examples right when they find a model they want to use. This change is going to make it hard to replace the variables in the code snippets.

**Comment by Alfrick** [comment]
@iankelk please share your thoughts about this.

**Pull request merged**
