### PR TITLE
[LT-3325] Add deprecation of PostSearches under Upcoming API Changes

### PR DESCRIPTION
**Pull request by tiit-clarifai**
https://clarifai.atlassian.net/browse/LT-3325

### CODE REVIEW

**Comment by yangshengBE** [comment]
have we reached out to sales team about this change? need to make sure customers fully migrated before we remove this.

**Review by yangshengBE — APPROVED** [review]

**Comment by tiit-clarifai** [comment]
> have we reached out to sales team about this change?

I have not. Who would be a contact in the sales team that we should notify?

> need to make sure customers fully migrated before we remove this.

No plans to fully remove it yet, just marking as deprecated for now.

**Comment by yangshengBE** [comment]
> > have we reached out to sales team about this change?
> 
> I have not. Who would be a contact in the sales team that we should notify?
> 
> > need to make sure customers fully migrated before we remove this.
> 
> No plans to fully remove it yet, just marking as deprecated for now.

yeah just realize that the main info here is not receiving any update.

> Who would be a contact in the sales team that we should notify?

i sugget to reach out # support-team and start from there

**Comment by Alfrick** [comment]
If the change has already been implemented in the API, I think the deprecation notice should appear under the **Completed Changes** heading.

**Pull request merged**
